# Generated by Django 4.1.3 on 2022-11-24 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_holder_report_header_report_rows'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='type_of_report',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_row', models.ManyToManyField(blank=True, to='app.holder')),
            ],
        ),
        migrations.AlterField(
            model_name='report',
            name='rows',
            field=models.ManyToManyField(blank=True, related_name='row', to='app.row'),
        ),
    ]
