# Generated by Django 4.1.3 on 2022-11-24 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_remove_report_created_by_remove_report_header_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='table',
            name='type_of_report',
        ),
        migrations.AddField(
            model_name='report',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='type_of_report',
            field=models.TextField(blank=True),
        ),
    ]
