# Generated by Django 4.1.3 on 2022-11-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_table_created_by_remove_table_type_of_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='row_head_name',
            field=models.TextField(blank=True),
        ),
    ]
